### ISSUE TITLE
[issue] Better experiment for startup

### ISSUE THREAD

**Issue by huang12zheng** [GitJournal/GitJournal#404]
## purpose
*  How do you document and discuss these issues with Startup

something like :
1. mismatch when pub get
2. build error
3. version suggestion 
## Description
* case1 - mismatch

Automatically generate as follow, that would get a mismatch.
```yaml
file_picker: ^2.0.7 <<< I forget
dependency_overrides:
  markdown:
    git: https://github.com/GitJournal/markdown.git
  # Required for screenshots package
  process: ^4.0.0-nullsafety.1
  platform: ^3.0.0-nullsafety.4 <<<<<
  file: ^6.0.0-nullsafety.1

```
run well
```
file_picker: 2.0.7
platform: 3.0.0-nullsafety.1
```
* case 2 - build error and version suggestion
like #381 and #401

> PS: #381 maybe Drop into the source code, nor just doc
